from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

# ── 1. Manager -> Architect ──────────────────────────────────────────────────

class TaskTicket(BaseModel):
    """
    Generated by the Manager agent. Represents a normalized version of the 
    user's raw prompt enriched with memory context.
    """
    intent: str = Field(description="The primary goal (e.g., 'feature', 'bugfix', 'refactor', 'question').")
    user_prompt: str = Field(description="The original or cleaned up prompt from the user.")
    user_preferences: str = Field(description="Relevant style or coding preferences from Mem0.")
    project_context: str = Field(description="Relevant snippets from the Airweave knowledge base.")
    affected_components: List[str] = Field(description="List of files or logical areas likely to be changed.")

# ── 2. Architect -> Developer ────────────────────────────────────────────────

class FileChangeSpec(BaseModel):
    file_path: str = Field(description="Absolute or root-relative path to the file.")
    action: str = Field(description="'CREATE', 'MODIFY', or 'DELETE'")
    instructions: str = Field(description="Detailed instructions on what the code inside this file must do.")

class ArchitectureSpec(BaseModel):
    """
    Generated by the Architect. A strict blueprint for the Developer.
    """
    summary: str = Field(description="High-level summary of the architectural changes.")
    files_to_change: List[FileChangeSpec] = Field(description="List of exact files to touch and how.")
    dependencies_to_add: List[str] = Field(description="New packages to install, if any.")
    test_requirements: str = Field(description="A bulleted list of assertions the Tester agent must verify.")

# ── 3. Developer -> Tester ───────────────────────────────────────────────────

class CodePatch(BaseModel):
    """
    Generated by the Developer. Represents the completion of typing code.
    """
    branch_name: str = Field(description="The Git branch where these changes were made (if using git loop) or 'local'.")
    files_modified: List[str] = Field(description="List of files actually modified.")
    commit_message: str = Field(description="A descriptive commit message for the batch of work.")
    ready_for_test: bool = Field(description="If True, Developer believes the code is complete and compiles.")

# ── 4. Tester -> Developer/Critic ────────────────────────────────────────────

class TestResult(BaseModel):
    """
    Generated by the Tester after running the sandbox.
    """
    passed: bool = Field(description="True if all tests/checks passed, False if any failed.")
    logs: str = Field(description="Relevant stdout/stderr logs from the execution environment.")
    error_summary: str = Field(description="If failed, a concise summary of WHY it failed to guide the Developer.")

# ── 5. Critic -> User/Developer ──────────────────────────────────────────────

class ReviewReport(BaseModel):
    """
    Generated by the Critic. A static code analysis and style review.
    """
    approved: bool = Field(description="True if the code meets all style/architecture standards.")
    feedback: str = Field(description="Constructive feedback for the user or the Developer.")
    security_concerns: List[str] = Field(description="Any security risks introduced by the patch.")
